jenkins:
  securityRealm: #an authentication mechanism
    local: #basic authentication - ID/username & password
      allowsSignup: false #prevents anonymous users from creating an account
      users:
       - id: ${JENKINS_ADMIN_ID}
         password: ${JENKINS_ADMIN_PASSWORD}
  authorizationStrategy:
    globalMatrix:
      permissions:
        - "Overall/Administer:admin"
        - "Overall/Read:authenticated"
    

unclassified:
  location:
    url: http://jenkins:8080/