---
- name: Installing kubernetes packages on all hosts...
  hosts: all
  roles:
    - install-kubernetes-packages

- name: Disabling swap on all hosts...
  hosts: all
  roles:
    - disable-swap

- name: Configuring networks on hosts...
  hosts: all
  roles:
    - configure-network-rules

- name: Installing kubectl on master node...
  hosts: controllers
  roles:
    - install-kubectl

- name: Deploying kubernetes cluster...
  hosts: controllers
  roles:
    - deploy-kubernetes

- name: Getting token from the master node...
  hosts: controllers
  roles:
    - get-join-command

- name: Joining workers to the cluster...
  hosts: workers
  roles:
    - join-cluster

- name: Starting installation of Helm...
  hosts: controllers
  roles:
    - install-helm

