apiVersion: argoproj.io/v1alpha1 
kind: Application
metadata:
  name: bookmaker
  namespace: argocd
  # finalizers:
  #   - resources-finalizer.argocd.argoproj.io

spec:
  project: default

  source:
    path: app/chart
    repoURL: git@github.com:Slvr-one/bookmaker.git
    targetRevision: HEAD
    directory:
      recurse: true

  destination: 
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated: 
      selfHeal: true 
      prune: true