# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: efk-logging
#   namespace: argocd #efk

# spec:
#   project: default
  
#   source:
#     path: ./ #charts/efk-logging/charts
#     repoURL: https://github.com/cdwv/efk-stack-helm.git #git@github.com:Slvr-one/porfolio-config.git
#     targetRevision: HEAD
#     # directory:
#     #   recurse: true
  
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: efk

#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#     syncOptions:
#     - CreateNamespace=true