apiVersion: v1
kind: Service
metadata:
  name: {{ include "BM.fullname" . }}-app
  labels:
    {{- include "BM.labels" . | nindent 4 }}
    app: bookmaker
spec:
  {{- if not .Values.ingress.enabled }}
  type: LoadBalancer
  {{- end }}
  sessionAffinity: None
  ports:
  - port: {{ .Values.services.app.servicePort }}
    # name: web
    targetPort: {{ .Values.services.app.targetPort }}
  selector:
    {{- include "BM.selectorLabels" . | nindent 4 }}
  
