apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.env }}-ssl-cert
  namespace: default
spec:
  secretName: {{ .Values.env }}-ssl-cert
  issuerRef:
    name: {{ .Values.env }}-letsencrypt
    kind: ClusterIssuer
  commonName: {{ .Values.user.host }} 
  dnsNames:
  - {{ .Values.user.host }}
