apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.env }}-letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory  #"-staging"
    email: {{ .Values.user.email }}
    privateKeySecretRef:
      name: {{ .Values.env }}-letsencrypt 
    solvers:
    - http01:
       ingress:
         class: {{ .Values.ingress.class }}