apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "BM.fullname" . }}-app
data:
  release: {{ include "BM.fullname" . }}
  service: {{ include "BM.fullname" . }}-mongodb-headless
  PERSISTENCY: {{ .Values.persistency | quote }}
  LOG_LEVEL: {{ .Values.logLevel }}