apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "BM.fullname" . }}-app
  labels:
    date: {{ now | htmlDate }}
    version: {{ .Chart.Version }}
    {{- include "BM.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ include "BM.fullname" . }}
    helm.sh/chart: {{ include "BM.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.Version }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}

spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      {{- include "BM.selectorLabels" . | nindent 6 }}  
  template:
    metadata:
      labels:
        {{- include "BM.labels" . | nindent 8 }}
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets }}
      {{- end }}
      containers:
      - image: "{{ .Values.app.image }}:{{ .Values.app.imageTag }}"
        name: {{ include "BM.fullname" . }}-app
        ports:
        - containerPort: {{ .Values.services.app.targetPort }}
        # livenessProbe:
        #   httpGet:
        #     path: /
        #     port: app
        # readinessProbe:
        #   httpGet:
        #     path: /
        #     port: app
        envFrom:
        - configMapRef:
            name: {{ include "BM.fullname" . }}-app
        - secretRef:
            name: {{ include "BM.fullname" . }}-mongo
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"