apiVersion: argoproj.io/v1alpha1 
kind: Application
metadata:
  name: infra
  namespace: argocd

spec:
  project: default

  source:
    repoURL: git@github.com:Slvr-one/porfolio-config.git
    targetRevision: HEAD
    path: apps
    directory:
      recurse: true
      
  destination: 
    server: https://kubernetes.default.svc
    # namespace: default

  syncPolicy:
    automated: 
      selfHeal: true 
      prune: true
      # allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    # - Validate=false
    # - ApplyOutOfSyncOnly=true
    # - PrunePropagationPolicy=foreground
    # - PruneLast=true