apiVersion: v1
kind: Secret
metadata:
  name: config-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: git@github.com:Slvr-one/k8s-dev
  sshPrivateKey: |
