# helm registry - artifact hub  
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: asia-northeast1-helm-registry
spec:
  backendType: gcpSecretsManager
  projectId: PROJECT_NAME
  data:
  - key: argocd-helm-login-key # secret manager name
    name: key
    version: latest
  template:
    metadata:
      namespace: argocd
      labels:
        argocd.argoproj.io/secret-type: repository
    stringData:
      enableOCI: "true"
      url: asia-northeast1-docker.pkg.dev
      name: asia-northeast1-helm-registry
      # https://cloud.google.com/artifact-registry/docs/helm/authentication#json-key
      username: _json_key_base64
      password: <%= data.key %>
      type: helm

--- 

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: example
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secretstore-sample
    kind: SecretStore
  target:
    name: secret-to-be-created
    creationPolicy: Owner
  data:
  - secretKey: secret-key-to-be-managed
    remoteRef:
      key: provider-key
      version: provider-key-version
      property: provider-key-property
  dataFrom:
  - extract:
      key: remote-key-in-the-provider
