# Default values for bookmaker_v4.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: "dvir-bm"
# version: "0.0.1"

# Bookmaker app
app:
  image: "839821061981.dkr.ecr.eu-central-1.amazonaws.com/bookmaker"
  imageTag: 1.0.0
  replicas: 3
  pullPolicy: Always

services:
  app:
    targetPort: 5000
    # bookmaker service endpoint:
    servicePort: 80

# env-vars for bookmaker app:
persistency: yes
logLevel: "info"

# Environment for certificate issues:
env: "prod" #/ "staging"

# Ingress config:
ingress:
  enabled: yes
  class: "nginx"
  # className: ""
  # annotations: {}
  #   # kubernetes.io/ingress.class: nginx
  #   # kubernetes.io/tls-acme: "true"
  # hosts:
  #   - host: sample-app.local
  #     paths:
  #       - path: /
  #         pathType: ImplementationSpecific
  # tls: []
  # #  - secretName: sample-app-tls
  # #    hosts:
  # #      - sample-app.local

# MongoDB reset with cronJob:
cronJob:
  enabled: no
  # schedule: "0 0 * * *" #once a day - midnight (@daily)

# User detailes:
user:
  # Domain for ingress routing:   #IP.nip.io
  host: "dviross.zapto.org"  
  # Email for CA cert managing
  email: "dviross@outlook.com"
  # Time-zone for precise cron job
  timeZone: "Asia/Jerusalem" # "Etc/UTC"   # IL  ("IST/IDT")

#mongodb - overrides:
mongodb:
  architecture: replicaset
  replicaCount: 3
  auth:
    enabled: yes
    rootUser: "dviross"
    rootPassword: "secretpass"

  # Set this value to the name of the Secret created by any of
  # the MongoDB Operators, containing the `connectionString.standardSrv`
  # attribute, used to connect to MongoDB.
  #
  # The Secret's name will always be:
  #
  # - <resource-name>-<database>-<user>
  #
  # In the same namespace that the resource was created.
  connectionStringSecret: "<resource-name>-<database>-<user>"


resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}