# Default values for bookmaker_v4.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: "dvir-bm"
# version: "0.0.1"

# Bookmaker app
app:
  image: "839821061981.dkr.ecr.eu-central-1.amazonaws.com/bookmaker"
  tag: 1.0.0
  replicas: 3

services:
  app:
    targetPort: 5000
    # bookmaker service endpoint:
    servicePort: 80

# env-vars for bookmaker app:
persistency: yes
logLevel: "info"

# Environment for certificate issues:
env: "prod" #/ "staging"

# Ingress config:
ingress:
  enabled: yes
  class: "nginx"

# MongoDB reset with cronJob:
cronJob:
  enabled: no
  # schedule: "0 0 * * *" #once a day - midnight (@daily)

# User detailes:
user:
  # Domain for ingress routing:   #IP.nip.io
  host: "dviross.zapto.org"  
  # Email for CA cert managing
  email: "dviross@outlook.com"
  # Time-zone for precise cron job
  timeZone: "Asia/Jerusalem" # "Etc/UTC"   # IL  ("IST/IDT")

#mongodb - overrides:
mongodb:
  architecture: replicaset
  replicaCount: 3
  auth:
    enabled: yes
    rootUser: "dviross"
    rootPassword: "secretpass"