apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd #nginx

spec:
  project: default

  source:
    chart: ingress-nginx
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.4.0
    # path: ingress-nginx
    helm:
      releaseName: ingress-nginx

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    syncOptions:
    - CeateNamespace=true
    automated:
      selfHeal: true
      prune: true

            
