# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: secret-manager
#   namespace: argocd #secret

# spec:
#   project: default

#   source:
#     chart: kubernetes-external-secrets
#     repoURL: https://external-secrets.github.io/kubernetes-external-secrets/
#     targetRevision: 8.5.5
#     # path: secret-manager
#     helm:
#       releaseName: secret-manager
  
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: default

#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#     syncOptions:
#     - CreateNamespace=true