name: Helm Chart CI

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Helm
      uses: azure/setup-helm@v1

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Set up KinD (Kubernetes in Docker)
      uses: helm/kind-action@v1.2.0

    - name: Install and configure Helm chart-testing
      uses: helm/chart-testing-action@v2.1.0

    - name: Run Helm chart-testing
      run: ct lint --config ct.yaml

    - name: Build Docker images
      run: |
        docker build -t my-image:latest .
        docker save my-image:latest | gzip > my-image.tar.gz

    - name: Deploy to Kubernetes
      run: |
        kubectl create namespace my-namespace
        helm upgrade --install --namespace my-namespace my-release ./path/to/chart
